language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - pip install Twisted

script: python -m unittest mpd.tests
