language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"
  - "pypy"

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install Twisted; fi

script: python -m unittest mpd.tests
